# ma_liste=[1, 2, 3, 4, 5]
# for i in ma_liste:
#     print(i**2)
# for i in range(10):
#     print(i**2)

# Indexage
loto = [1, 2, 3, 4, 5, 6, 7]
ville =["paris","londres","new york",]
# print(loto[0])
# print(ville[0])
# capitale_france=(ville[0])
# print(capitale_france)
# pour moodifier un element d une liste
# parexemple paris par bordezux
# ville[0]="bordezux"
# print(ville)
ville.append("marseille")
print(ville)